name: cr_calendar_plus
description: Awesome calendar with customizations, range picking and event showing.
version: 1.0.1
repository: https://github.com/lufimon/cr_calendar

topics:
  - widgets
  - user-interface
  - calendar
  - date
  - picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  jiffy: ^6.3.2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

